"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main4.py']
DATA_FILES = ["Klassen4.py", "Background1.jpg", "Background2.jpg", "Background3.jpg", "Background4.jpg", "Background5.jpg",
              "Andromeda-eR2n.ttf", "Spaceship_Blue.png", "Spaceship_flame.gif", "Spaceship_Green.png",
              "Spaceship_Red.png", "Spaceship_transparent.png", "Spaceship_transparent2.png", "Spaceship_Yellow.png",
              "Tacho.png", "Tacho1.png", "Tacho2.png", "Sound.wav"]
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
